#!/usr/bin/env python3
"""Generate Gate 3 technical artifacts from human-approved mapping rows.

Input is a JSON file written by the coordinator after the Gate 3 decision.  No
row is emitted unless its approval is explicitly ``APROVADO``.  This script
does not write to Revit or validate an IFC; those actions remain Gates 4 and 5.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from collections import defaultdict
from pathlib import Path
from xml.etree.ElementTree import Element, ElementTree, SubElement, indent


APPROVED = "APROVADO"
SHARED_TYPES = {"TEXT": "TEXT", "INTEGER": "INTEGER", "NUMBER": "NUMBER", "YESNO": "YESNO", "LENGTH": "LENGTH", "AREA": "AREA", "VOLUME": "VOLUME", "ANGLE": "ANGLE"}


def value(row: dict, *names: str) -> str:
    for name in names:
        candidate = row.get(name)
        if candidate is not None and str(candidate).strip():
            return str(candidate).strip()
    return ""


def approved(row: dict) -> bool:
    return value(row, "gate3_approval", "Aprovacao_Gate_3", "approval").upper() == APPROVED


def valid_guid(raw: str) -> str:
    try:
        return str(uuid.UUID(raw))
    except (ValueError, AttributeError) as error:
        raise ValueError(f"GUID inválido ou ausente: {raw or '(vazio)'}.") from error


def clean(value_: str) -> str:
    return re.sub(r"[\t\r\n]+", " ", value_).strip()


def shared_parameter_text(rows: list[dict]) -> bytes:
    shared = [row for row in rows if value(row, "classification", "Classificacao") == "PARAMETRO_COMPARTILHADO"]
    groups = sorted({value(row, "parameter_group", "Grupo_Parametro") or "BIM IFC" for row in shared})
    ids = {group: str(index + 1) for index, group in enumerate(groups)}
    lines = [
        "# This is a Revit shared parameter file.",
        "# Generated by Information Manager IFC — Gate 3 approved rows only.",
        "*META\tVERSION\tMINVERSION", "META\t2\t1", "*GROUP\tID\tNAME",
        *[f"GROUP\t{ids[group]}\t{clean(group)}" for group in groups],
        "*PARAM\tGUID\tNAME\tDATATYPE\tDATACATEGORY\tGROUP\tVISIBLE\tDESCRIPTION\tUSERMODIFIABLE\tHIDEWHENNOVALUE",
    ]
    for row in shared:
        name = value(row, "revit_parameter", "Parametro_Revit_Candidato")
        if not name:
            raise ValueError(f"{value(row, 'requirement_code', 'Codigo_Requisito')}: parâmetro Revit ausente.")
        datatype = value(row, "revit_datatype", "Tipo_Dado_Revit", "Tipo_Dado_Esperado").upper() or "TEXT"
        if datatype not in SHARED_TYPES:
            raise ValueError(f"{name}: datatype Revit não suportado para TXT: {datatype}.")
        group = value(row, "parameter_group", "Grupo_Parametro") or "BIM IFC"
        lines.append("\t".join(["PARAM", valid_guid(value(row, "guid", "GUID")), clean(name), SHARED_TYPES[datatype], "", ids[group], "1", clean(value(row, "description", "Descricao")), "1", "0"]))
    return ("\r\n".join(lines) + "\r\n").encode("utf-16le")


def spt_manifest(rows: list[dict]) -> ElementTree:
    root = Element("SharedParametersToolManifest", {"version": "1.0", "status": "Gate3Approved"})
    root.append(Element("Notice"))
    root[-1].text = "Use as an auditable setup manifest; confirm import compatibility with the installed Autodesk Shared Parameters Tool version."
    for row in rows:
        if value(row, "classification", "Classificacao") != "PARAMETRO_COMPARTILHADO":
            continue
        parameter = SubElement(root, "Parameter", {
            "guid": valid_guid(value(row, "guid", "GUID")),
            "name": value(row, "revit_parameter", "Parametro_Revit_Candidato"),
            "scope": (value(row, "revit_scope", "Escopo_Revit") or "INSTANCE").upper(),
            "groupUnder": value(row, "revit_group_under", "Grupo_Revit") or "Data",
        })
        for category in row.get("revit_categories", row.get("Categorias_Revit", [])) or []:
            SubElement(parameter, "Category", {"name": str(category)})
    return ElementTree(root)


def psets_text(rows: list[dict]) -> str:
    grouped: dict[tuple[str, str, str], list[dict]] = defaultdict(list)
    for row in rows:
        if value(row, "destination_type", "Destino_IFC_Tipo_Candidato") != "CUSTOM_PSET":
            continue
        pset, scope, ifc_class = value(row, "pset", "Pset_Candidato"), value(row, "revit_scope", "Escopo_Revit"), value(row, "ifc_class", "Classe_IFC_Candidata")
        if not (pset and ifc_class):
            raise ValueError(f"{value(row, 'requirement_code', 'Codigo_Requisito')}: CUSTOM_PSET exige Pset e classe IFC.")
        grouped[(pset, (scope or "INSTANCE").upper(), ifc_class)].append(row)
    lines = ["# User Defined PropertySet Definition File", "# Gate 3 — linhas aprovadas. Sintaxe do exportador IFC Autodesk.", ""]
    for (pset, scope, ifc_class), members in sorted(grouped.items()):
        lines.append(f"PropertySet:\t{clean(pset)}\t{'T' if scope == 'TYPE' else 'I'}\t{clean(ifc_class)}")
        for row in members:
            property_ = value(row, "property", "Propriedade_Candidata")
            parameter = value(row, "revit_parameter", "Parametro_Revit_Candidato")
            datatype = value(row, "ifc_data_type", "Tipo_Dado_IFC") or "Text"
            if not (property_ and parameter):
                raise ValueError(f"{value(row, 'requirement_code', 'Codigo_Requisito')}: CUSTOM_PSET exige propriedade IFC e parâmetro Revit.")
            lines.append(f"\t{clean(property_)}\t{clean(datatype)}\t{clean(parameter)}")
        lines.append("")
    return "\r\n".join(lines) + "\r\n"


def model_checker(rows: list[dict]) -> ElementTree:
    root = Element("MCSettings", {"AllowRequired": "False", "Name": "Gate 3 — Parâmetros IFC", "Author": "Information Manager IFC", "Description": "Checa presença de parâmetros aprovados antes da exportação IFC.", "Image": "", "LastModified": "0"})
    heading = SubElement(root, "Heading", {"ID": str(uuid.uuid5(uuid.NAMESPACE_URL, "gate3-heading")), "HeadingText": "Gate 3 — Dados aprovados", "Description": "Falhas bloqueiam a exportação.", "IsChecked": "True"})
    section = SubElement(heading, "Section", {"ID": str(uuid.uuid5(uuid.NAMESPACE_URL, "gate3-section")), "SectionName": "Parâmetros", "Title": "", "IsChecked": "True", "Description": "Parâmetros compartilhados aprovados."})
    for index, row in enumerate(rows):
        parameter = value(row, "revit_parameter", "Parametro_Revit_Candidato")
        if not parameter:
            continue
        code = value(row, "requirement_code", "Codigo_Requisito") or str(index + 1)
        check = SubElement(section, "Check", {"ID": str(uuid.uuid5(uuid.NAMESPACE_URL, f"gate3-check-{code}-{parameter}")), "CheckName": f"{code} — {parameter} vazio", "Description": "Parâmetro obrigatório aprovado no Gate 3.", "FailureMessage": f"Preencher {parameter} antes da exportação IFC.", "ResultCondition": "FailMatchingElements", "CheckType": "Custom", "IsRequired": "True", "IsChecked": "True"})
        SubElement(check, "Filter", {"ID": str(uuid.uuid5(uuid.NAMESPACE_URL, f"gate3-filter-{code}-{parameter}")), "Operator": "And", "Category": "Parameter", "Property": parameter, "Condition": "HasNoValue", "Value": "True", "CaseInsensitive": "False", "Unit": "None", "UnitClass": "None", "FieldTitle": "", "UserDefined": "False", "Validation": "None"})
    return ElementTree(root)


def main() -> int:
    parser = argparse.ArgumentParser(description="Gera artefatos Gate 3 de linhas aprovadas.")
    parser.add_argument("mapping", type=Path, help="JSON com chave rows e aprovação explícita por linha")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        payload = json.loads(args.mapping.read_text(encoding="utf-8"))
        rows = payload.get("rows", payload) if isinstance(payload, dict) else payload
        if not isinstance(rows, list):
            raise ValueError("O mapeamento deve conter uma lista rows.")
        selected = [row for row in rows if isinstance(row, dict) and approved(row)]
        if not selected:
            raise ValueError("Nenhuma linha possui aprovação explícita APROVADO no Gate 3.")
        args.output.mkdir(parents=True, exist_ok=True)
        (args.output / "parametros_compartilhados_gate3.txt").write_bytes(b"\xff\xfe" + shared_parameter_text(selected))
        for filename, tree in (("shared_parameters_tool_manifest_gate3.xml", spt_manifest(selected)), ("model_checker_gate3.xml", model_checker(selected))):
            indent(tree, space="  ")
            tree.write(args.output / filename, encoding="utf-8", xml_declaration=True)
        (args.output / "user_defined_psets_gate3.txt").write_text(psets_text(selected), encoding="utf-8", newline="")
        evidence = {"gate": 3, "status": "READY_FOR_GATE_4_PROOF", "source": str(args.mapping.name), "approved_requirement_count": len(selected), "queries": [{"requirement_code": value(row, "requirement_code", "Codigo_Requisito"), "ifc_class": value(row, "ifc_class", "Classe_IFC_Candidata"), "destination_type": value(row, "destination_type", "Destino_IFC_Tipo_Candidato"), "attribute": value(row, "attribute", "Atributo_IFC_Candidato"), "pset": value(row, "pset", "Pset_Candidato"), "property": value(row, "property", "Propriedade_Candidata"), "qto": value(row, "quantity_set", "QuantitySet_Candidato"), "quantity": value(row, "quantity_name", "QuantityName_Candidato")} for row in selected], "limitation": "Plano de consulta para Bonsai/IfcOpenShell. O Gate 4 deve comprovar o IFC real."}
        (args.output / "bonsai_evidence_plan_gate4.json").write_text(json.dumps(evidence, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps({"status": "success", "output": str(args.output), "approved_rows": len(selected), "artifacts": sorted(path.name for path in args.output.iterdir())}, ensure_ascii=False))
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(json.dumps({"status": "error", "summary": str(error)}, ensure_ascii=False), file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
